### ISSUE TITLE
Fehler Aufgaben Kapitel 3

### ISSUE THREAD

**Issue by hb9hnt** [puremath/pythonbuch#6]
Im Kapitel 3 wird in einer Aufgabe noch IDLE erwähnt und die Python-Konsole wird Prompt genannt. Das sollte einheitlich sein.

**Comment by chunyboy** [comment]
Dann benutzen wir doch durchgehend das Wort Python-Konsole.

**Comment by hb9hnt** [comment]
@chunyboy Ja, ich ändere das. Ich werde eine weitere Branch namens "Schreibfehler" erstellen, in der man so kleine Änderungen committen kann. Diese können wir dann jeweils in Develeop und Master mergen. So müssen wir auf die Fehlerkorrektur nicht bis im nächsten Sommer warten.
